name: Geode-CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: geode-ci-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: dotnet build ./Geode.sln --no-restore
    - name: Test
      working-directory: ./src/Geode.Tests
      run: dotnet test
