name: Publish to NuGet

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Geode

    - name: Build
      run: dotnet build --no-restore --configuration Release ./src/Geode

    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/Geode.Tests

    - name: Pack
      run: dotnet pack --no-build --configuration Release --output out ./src/Geode

    - name: Push
      run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json